import type { NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Anony Sender</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-screen h-screen flex flex-col items-center justify-center">
                <h1 className="logo text-3xl mb-5">Anony Sender</h1>
                <p className="w-1/2 mb-3 text-white/60">
                    Are you looking to ask your friends a question and not know who said what? Then
                    you have come to the right place.
                </p>
                <p className="w-1/2 mb-10 text-white/60">
                    Anony Sender caters for that very need of posing a question to your mates and
                    having them being at peace knowing that they will not be completely ANONYMOUS!
                </p>
                <button
                    className="btn-grad"
                    onClick={() => signIn("google", { callbackUrl: "/profile" })}>
                    Continue with Google
                </button>
            </main>
        </div>
    );
};

export default Home;
